import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/store/provider';
//import ReactQueryProvider from '@/react-query/provider';
// import { ApolloProvider } from '@apollo/client';
// import apolloClient from '@/apollo-client';
//import ApolloProviderWrapper from '@/apollo-provider';
import ThemeProvider from '@/styled-components/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
